# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 70, 320, 490))
        self.label.setStyleSheet("border-image:url(:/images/loginback.png);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 70, 401, 490))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(410, 210, 361, 331))
        self.widget_2.setObjectName("widget_2")
        self.login_username_input = QtWidgets.QLineEdit(self.widget_2)
        self.login_username_input.setGeometry(QtCore.QRect(30, 40, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.login_username_input.setFont(font)
        self.login_username_input.setStyleSheet("border:1px solid rgba(0,0,0);\n"
"border-radius:8px")
        self.login_username_input.setObjectName("login_username_input")
        self.login_password_input = QtWidgets.QLineEdit(self.widget_2)
        self.login_password_input.setGeometry(QtCore.QRect(30, 110, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.login_password_input.setFont(font)
        self.login_password_input.setStyleSheet("border:1px solid rgba(0,0,0);\n"
"border-radius:8px")
        self.login_password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_password_input.setObjectName("login_password_input")
        self.login_button = QtWidgets.QPushButton(self.widget_2)
        self.login_button.setGeometry(QtCore.QRect(30, 220, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("#login_button{\n"
"background-color: rgb(0, 0, 0);\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#login_button:hover{\n"
"background-color: rgb(252, 252, 252);\n"
"    color:rgb(0,0,0);\n"
"}\n"
"#login_button:pressed{\n"
"        padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"\n"
"")
        self.login_button.setObjectName("login_button")
        self.is_remember_checkbox = QtWidgets.QCheckBox(self.widget_2)
        self.is_remember_checkbox.setGeometry(QtCore.QRect(30, 180, 54, 13))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.is_remember_checkbox.setFont(font)
        self.is_remember_checkbox.setObjectName("is_remember_checkbox")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(695, 80, 81, 41))
        self.widget_3.setStyleSheet("#close_button{\n"
"border:none;\n"
"}\n"
"#close_button:hover{\n"
"    \n"
"    background-color: rgb(255, 85, 127);\n"
"}\n"
"#close_button:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minus_button = QtWidgets.QPushButton(self.widget_3)
        self.minus_button.setStyleSheet("#minus_button{\n"
"border:none;\n"
"}\n"
"#minus_button:hover{\n"
"    \n"
"    background-color: rgb(211, 211, 211);\n"
"    \n"
"}\n"
"#minus_button:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.minus_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minus_button.setIcon(icon)
        self.minus_button.setIconSize(QtCore.QSize(20, 20))
        self.minus_button.setObjectName("minus_button")
        self.horizontalLayout_2.addWidget(self.minus_button)
        self.close_button = QtWidgets.QPushButton(self.widget_3)
        self.close_button.setEnabled(True)
        self.close_button.setMaximumSize(QtCore.QSize(71, 71))
        self.close_button.setStyleSheet("#close_button{\n"
"border:none;\n"
"}\n"
"#close_button:hover{\n"
"    \n"
"    background-color: rgb(255, 85, 127);\n"
"}\n"
"#close_button:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.close_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon1)
        self.close_button.setIconSize(QtCore.QSize(20, 20))
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 160, 231, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.close_button.clicked.connect(MainWindow.close) # type: ignore
        self.minus_button.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_username_input.setPlaceholderText(_translate("MainWindow", "账号:"))
        self.login_password_input.setPlaceholderText(_translate("MainWindow", "密码:"))
        self.login_button.setText(_translate("MainWindow", "登录"))
        self.is_remember_checkbox.setText(_translate("MainWindow", "记住"))
        self.label_3.setText(_translate("MainWindow", "SCNU空间预约"))
import resource_rc
